### ISSUE TITLE
Menu stop working

### ISSUE THREAD

**Issue by adx74** [JCR64/GarlicOS-MinUIfied#2] opened 2024-01-04 23:00 UTC
Hello, as soon as i add your theme, i can no longer open the menu to return at garlic when i'm inside a game.

**Comment by JCR64** [comment] 2024-01-04 23:40
Hmm that is very strange. I recommend restoring the default files from [GarlicOS 1.4.9](https://www.patreon.com/posts/garlicos-for-76561333) to see if that fixes the issue.

Start off with just `retroarch.cfg` because that can sometimes cause problems. Then if it is still not working best thing would be to restore rest of the default skin files and see if that fixes it. Absolute worse case scenario would be to do fresh install of GarlicOS (make sure you backup your games/saves).

The theme shouldn't really interfere with how GarlicOS/RetroArch works so not sure what the problem is, sorry!

**Comment by JCR64** [comment] 2024-02-03 17:17
I haven't been able to replicate this issue exactly but I have had similar issues after using the reset button. The main file being affected is `retroarch.cfg` with issues such as:
- button inputs not working in a game
- yellow RetroArch notification when loading a game
- GarlicOS menus going haywire (similar to a VCR player effect)

It's rare but `coremapping.json` can also be affected:
- console folders disappear from the GarlicOS menu

In both cases restoring a backup of those files fixes the issue.

Recommendations:
a) not using the reset button
b) having a backup of `retroarch.cfg` and `coremapping.json` ready to use 

XQuader has a great script that can be run from APPS on the device itself to restore those files, it's available on the RG35XX website in Apps for GarlicOS called "Backup/Restore". Anyway as I don't think this issue is with the theme itself but a 'quirk' of the device/GarlicOS I will close it.

**Closed as completed by JCR64** 2024-02-03 17:17 UTC
